echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am from batch-33 and learning git/github to improve my skills"
echo "After Git we will learn about Docker and Kubernetes"
echo " I am Mrinal Mondal"
echo "I want Learn Fortinet Firewall"
echo "I want to learn Routing"
echo "Our new batch will start on 4th Oct"
echo"I will be there Hinjewadi office on Sunday"
echo "Today I am Learning Merge conflict"
